"""empty message

Revision ID: 175301776293
Revises: f6be4c6dd9af
Create Date: 2023-12-03 20:52:24.129300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '175301776293'
down_revision: Union[str, None] = 'f6be4c6dd9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'time_end',
               existing_type=postgresql.TIME(),
               type_=sa.Time(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'time_end',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
