"""empty message

Revision ID: 35037d2fce24
Revises: aaa46b94f97d
Create Date: 2023-10-20 14:34:58.253927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35037d2fce24'
down_revision: Union[str, None] = 'aaa46b94f97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('remainder_time', 'time_to_remaind',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('remainder_time', 'time_to_remaind',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
