"""empty message

Revision ID: 61e8fa4c88f3
Revises: 6c3ffb56c3b8
Create Date: 2023-10-22 22:20:06.305464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e8fa4c88f3'
down_revision: Union[str, None] = '6c3ffb56c3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
