"""empty message

Revision ID: 687c8892373b
Revises: 
Create Date: 2023-10-15 20:46:15.150203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687c8892373b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_created_at'), 'event', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_date_end'), 'event', ['date_end'], unique=False)
    op.create_index(op.f('ix_event_date_start'), 'event', ['date_start'], unique=False)
    op.create_index(op.f('ix_event_event_name'), 'event', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_index(op.f('ix_event_time_end'), 'event', ['time_end'], unique=False)
    op.create_index(op.f('ix_event_time_start'), 'event', ['time_start'], unique=False)
    op.create_table('remainder_time',
    sa.Column('time_to_remaind', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remainder_time_id'), 'remainder_time', ['id'], unique=False)
    op.create_index(op.f('ix_remainder_time_time_to_remaind'), 'remainder_time', ['time_to_remaind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remainder_time_time_to_remaind'), table_name='remainder_time')
    op.drop_index(op.f('ix_remainder_time_id'), table_name='remainder_time')
    op.drop_table('remainder_time')
    op.drop_index(op.f('ix_event_time_start'), table_name='event')
    op.drop_index(op.f('ix_event_time_end'), table_name='event')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_date_start'), table_name='event')
    op.drop_index(op.f('ix_event_date_end'), table_name='event')
    op.drop_index(op.f('ix_event_created_at'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
