"""empty message

Revision ID: 6c3ffb56c3b8
Revises: 152ecef032db
Create Date: 2023-10-22 21:47:31.069541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c3ffb56c3b8'
down_revision: Union[str, None] = '152ecef032db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_start', sa.Date(), server_default=sa.text('now()'), nullable=False))
    op.add_column('event', sa.Column('time_start', sa.Time(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('event', sa.Column('date_end', sa.Date(), nullable=True))
    op.add_column('event', sa.Column('time_end', sa.Time(timezone=True), nullable=True))
    op.drop_index('ix_event_datetime_end', table_name='event')
    op.drop_index('ix_event_datetime_start', table_name='event')
    op.create_index(op.f('ix_event_date_end'), 'event', ['date_end'], unique=False)
    op.create_index(op.f('ix_event_date_start'), 'event', ['date_start'], unique=False)
    op.create_index(op.f('ix_event_time_end'), 'event', ['time_end'], unique=False)
    op.create_index(op.f('ix_event_time_start'), 'event', ['time_start'], unique=False)
    op.drop_column('event', 'datetime_start')
    op.drop_column('event', 'datetime_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('datetime_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('datetime_start', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_event_time_start'), table_name='event')
    op.drop_index(op.f('ix_event_time_end'), table_name='event')
    op.drop_index(op.f('ix_event_date_start'), table_name='event')
    op.drop_index(op.f('ix_event_date_end'), table_name='event')
    op.create_index('ix_event_datetime_start', 'event', ['datetime_start'], unique=False)
    op.create_index('ix_event_datetime_end', 'event', ['datetime_end'], unique=False)
    op.drop_column('event', 'time_end')
    op.drop_column('event', 'date_end')
    op.drop_column('event', 'time_start')
    op.drop_column('event', 'date_start')
    # ### end Alembic commands ###
