"""empty message

Revision ID: 751b6ec8bd8b
Revises: de276f8888d3
Create Date: 2023-10-14 16:55:02.936718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751b6ec8bd8b'
down_revision: Union[str, None] = 'de276f8888d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remainder_time',
    sa.Column('time_to_remaind', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remainder_time_id'), 'remainder_time', ['id'], unique=False)
    op.create_index(op.f('ix_remainder_time_time_to_remaind'), 'remainder_time', ['time_to_remaind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remainder_time_time_to_remaind'), table_name='remainder_time')
    op.drop_index(op.f('ix_remainder_time_id'), table_name='remainder_time')
    op.drop_table('remainder_time')
    # ### end Alembic commands ###
