"""empty message

Revision ID: 9f38f761e31a
Revises: f993eebae1e7
Create Date: 2023-10-15 10:15:58.278171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f38f761e31a'
down_revision: Union[str, None] = 'f993eebae1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remainder_time', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'remainder_time', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'remainder_time', type_='foreignkey')
    op.drop_column('remainder_time', 'event_id')
    # ### end Alembic commands ###
