"""empty message

Revision ID: aaa46b94f97d
Revises: 4adec857d9d9
Create Date: 2023-10-20 14:05:12.072851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa46b94f97d'
down_revision: Union[str, None] = '4adec857d9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remainder_time', sa.Column('date_to_remaind', sa.Date(), nullable=True))
    op.create_index(op.f('ix_remainder_time_date_to_remaind'), 'remainder_time', ['date_to_remaind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remainder_time_date_to_remaind'), table_name='remainder_time')
    op.drop_column('remainder_time', 'date_to_remaind')
    # ### end Alembic commands ###
