version: "3.9"

services:
    db:
        image: postgres
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
        ports:
            - "${POSTGRES_PORT}:5432"

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy

    app:
        build: .
        # command: bash -c "cd app/database && alembic upgrade head && cd ../.. && python app/main.py"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy

volumes:
    postgres_data:
        driver: local
